name: Build and Publish to NuGet

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'
    
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=${{ env.GitVersion_MajorMinorPatch }}
    
    - name: Pack
      run: dotnet pack BlazorJsInteropGenerator/BlazorJsInteropGenerator.csproj --configuration Release --no-build -p:PackageVersion=${{ env.GitVersion_MajorMinorPatch }}
    
    - name: Publish to NuGet
      run: dotnet nuget push BlazorJsInteropGenerator/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate